# Generated by Django 4.2.8 on 2026-08-15 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='timeline',
            index=models.Index(fields=['capsule', 'event_date'], name='idx_timeline_capsule_date'),
        ),
    ]
