services:
  web:
    restart: always
    build: .
    container_name: web
    command: >
      sh -c "python manage.py collectstatic --noinput && python manage.py makemigrations && python manage.py migrate && gunicorn config.asgi:application -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:8000 --workers 4 --reload"
    volumes:
      - .:/app
    ports:
      - "${BACKEND_PORT:-8000}:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings
    env_file:
      - .env