# Generated by Django 4.2.8 on 2026-08-06 02:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Capsule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('profile', models.ImageField(upload_to='capsule_profiles')),
                ('cover', models.ImageField(upload_to='capsule_covers')),
                ('cover_thumbnail', models.ImageField(blank=True, null=True, upload_to='capsule_covers/thumbnails')),
                ('grid_x', models.IntegerField()),
                ('grid_y', models.IntegerField()),
                ('views', models.PositiveIntegerField(default=0)),
                ('likes', models.PositiveIntegerField(default=0)),
                ('is_public', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capsules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['grid_y', 'grid_x'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.PositiveIntegerField(default=0)),
                ('review', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('capsule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capsule.capsule')),
            ],
        ),
        migrations.AddIndex(
            model_name='capsule',
            index=models.Index(fields=['grid_x', 'grid_y'], name='idx_grid_position'),
        ),
        migrations.AddIndex(
            model_name='capsule',
            index=models.Index(fields=['is_public', 'grid_x', 'grid_y'], name='idx_public_grid'),
        ),
        migrations.AddConstraint(
            model_name='capsule',
            constraint=models.UniqueConstraint(fields=('grid_x', 'grid_y'), name='unique_grid_position'),
        ),
    ]
