# Generated by Django 4.2.8 on 2026-08-06 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capsule', '0002_review_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='capsule',
            name='title',
        ),
        migrations.AddField(
            model_name='capsule',
            name='bio',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='capsule',
            name='dob',
            field=models.DateField(default='2025-01-01'),
        ),
        migrations.AddField(
            model_name='capsule',
            name='location',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='capsule',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='capsule',
            name='story',
            field=models.TextField(default=''),
        ),
    ]
