# Generated by Django 4.2.8 on 2026-08-07 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capsule', '0003_remove_capsule_title_capsule_bio_capsule_dob_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capsule',
            name='grid_x',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='capsule',
            name='grid_y',
            field=models.IntegerField(default=0),
        ),
    ]
