# Generated by Django 4.2.8 on 2026-08-07 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capsule', '0005_view_like'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='view',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='view',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('user', 'capsule'), name='unique_user_capsule_view'),
        ),
        migrations.AddConstraint(
            model_name='view',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', True)), fields=('ip_address', 'capsule'), name='unique_ip_capsule_view'),
        ),
    ]
