# Generated by Django 5.1.4 on 2026-08-08 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capsule', '0006_alter_view_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='capsule',
            name='story',
        ),
    ]