# Generated by Django 4.2.8 on 2026-08-08 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capsule', '0007_remove_capsule_story'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='capsule',
            constraint=models.UniqueConstraint(fields=('user',), name='unique_user_capsule'),
        ),
    ]
