# Generated by Django 4.2.8 on 2026-08-12 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capsule', '0008_capsule_unique_user_capsule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='capsule',
            name='cover_thumbnail',
        ),
    ]
