# Generated by Django 4.2.8 on 2026-08-15 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capsule', '0009_remove_capsule_cover_thumbnail'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='like',
            unique_together=set(),
        ),
        migrations.AddIndex(
            model_name='capsule',
            index=models.Index(fields=['is_public', '-created_at'], name='idx_public_created'),
        ),
        migrations.AddIndex(
            model_name='capsule',
            index=models.Index(fields=['location'], name='idx_location'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['capsule', '-created_at'], name='idx_review_capsule_created'),
        ),
        migrations.AddConstraint(
            model_name='like',
            constraint=models.UniqueConstraint(fields=('user', 'capsule'), name='unique_user_capsule_like'),
        ),
    ]
